<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.seetest.apps.morgan_stanley.web.tests.Sanity" tests="4" time="37.287" ignored="0" failures="2" timestamp="16 May 2017 18:41:05 GMT" skipped="0" hostname="DrorStainberg" errors="0">
  <testcase name="verifyHomePageExternalLink" time="5.740" classname="com.seetest.apps.morgan_stanley.web.tests.Sanity"/>
  <testcase name="verifyHomePageExternalLink" time="8.383" classname="com.seetest.apps.morgan_stanley.web.tests.Sanity">
    <failure type="java.lang.AssertionError" message="Verify Twitter Icon expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Verify Twitter Icon expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.seetest.framework.BasePage.seeTestAssert(BasePage.java:36)
	at com.seetest.apps.morgan_stanley.web.pages.HomePage.verifyTwitterIcon(HomePage.java:82)
	at com.seetest.apps.morgan_stanley.web.tests.Sanity.verifyHomePageExternalLink(Sanity.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verifyHomePageExternalLink -->
  <testcase name="VerfiyHomePageUI" time="10.573" classname="com.seetest.apps.morgan_stanley.web.tests.Sanity">
    <failure type="java.lang.AssertionError" message="Verify Ideas Tab expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Verify Ideas Tab expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.seetest.framework.BasePage.seeTestAssert(BasePage.java:36)
	at com.seetest.apps.morgan_stanley.web.pages.HomePage.verifyIdeasTab(HomePage.java:62)
	at com.seetest.apps.morgan_stanley.web.tests.Sanity.VerfiyHomePageUI(Sanity.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- VerfiyHomePageUI -->
  <testcase name="VerfiyHomePageUI" time="12.591" classname="com.seetest.apps.morgan_stanley.web.tests.Sanity"/>
</testsuite> <!-- com.seetest.apps.morgan_stanley.web.tests.Sanity -->
