<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.seetest.apps.eribank.tests.Sanity" tests="3" time="24.314" ignored="0" failures="0" timestamp="18 אפר 2018 14:22:32 GMT" skipped="1" hostname="AmitNahum" errors="1">
  <testcase name="VerfiyHomePageUI" time="24.313" classname="com.seetest.apps.eribank.tests.Sanity"/>
  <testcase name="VerfiyHomePageUI" time="0.001" classname="com.seetest.apps.eribank.tests.Sanity">
    <skipped/>
  </testcase> <!-- VerfiyHomePageUI -->
  <testcase name="beforeMethod" time="0.000" classname="com.seetest.apps.eribank.tests.Sanity">
    <error type="com.experitest.client.InternalException" message="The lockDeviceForExecution failed with error: &#039;Xpath illegal. Following xpath was provided: @name=&#039;Demo Cloud&#039;s iPhone 8 Plus B0166&#039;&#039;">
      <![CDATA[com.experitest.client.InternalException: The lockDeviceForExecution failed with error: 'Xpath illegal. Following xpath was provided: @name='Demo Cloud's iPhone 8 Plus B0166''
	at com.experitest.client.GridClient.lockDeviceForExecution(GridClient.java:394)
	at com.experitest.client.GridClient.lockDeviceForExecution(GridClient.java:227)
	at com.seetest.framework.BaseTest.createGridClient(BaseTest.java:69)
	at com.seetest.framework.BaseTest.beforeMethod(BaseTest.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
</testsuite> <!-- com.seetest.apps.eribank.tests.Sanity -->
